[build]
  base = "babs"
  command = "rm -rf node_modules package-lock.json && npm install && npm install @rollup/rollup-linux-x64-gnu --save-dev && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"

[[headers]]
  for = "/*.png"
  [headers.values]
    cache-control = "public, max-age=3600"

[[headers]]
  for = "/preview.png"
  [headers.values]
    cache-control = "public, max-age=3600"

[[headers]]
  for = "/splash.png"
  [headers.values]
    cache-control = "public, max-age=3600"

[[headers]]
  for = "/icon-192.png"
  [headers.values]
    cache-control = "public, max-age=3600"

[[headers]]
  for = "/index.html"
  [headers.values]
    cache-control = "public, max-age=300"

[[headers]]
  for = "/.well-known/farcaster.json"
  [headers.values]
    content-type = "application/json"
    cache-control = "public, max-age=3600"

# Removed redirect to allow local .well-known/farcaster.json to be served

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200