[build]
  base = "babs"
  command = "rm -rf node_modules package-lock.json && npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"

[[headers]]
  for = "/*.png"
  [headers.values]
    cache-control = "public, max-age=3600"

[[headers]]
  for = "/preview.png"
  [headers.values]
    cache-control = "public, max-age=3600"

[[headers]]
  for = "/splash.png"
  [headers.values]
    cache-control = "public, max-age=3600"

[[headers]]
  for = "/icon-192.png"
  [headers.values]
    cache-control = "public, max-age=3600"

[[redirects]]
  from = "/.well-known/farcaster.json"
  to = "https://api.farcaster.xyz/miniapps/hosted-manifest/01986682-efd2-a8bf-ab72-2622a37aeab2"
  status = 307

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200